# Generated by Django 4.1 on 2022-09-28 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productgallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductGallery',
        ),
    ]
