# Generated by Django 4.1 on 2022-09-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images1',
            field=models.ImageField(default='', upload_to='photos/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='images2',
            field=models.ImageField(default='', upload_to='photos/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(default='', upload_to='photos/products'),
        ),
    ]
