# Generated by Django 4.1 on 2022-10-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
    ]
