branch-defaults:
  master:
    environment: arprogears-env
    group_suffix: null
global:
  application_name: arprogears
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.7
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
