# Generated by Django 4.1 on 2022-09-12 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_options'),
        ('category', '0002_alter_category_slug'),
    ]

    operations = [
    ]
