# Generated by Django 4.1 on 2022-09-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_merge_20220912_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_image',
            field=models.ImageField(default='', upload_to='photos/categories/'),
        ),
    ]
