# Generated by Django 4.1 on 2022-10-03 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderproduct_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='discount',
        ),
    ]
